name: Ubuntu
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

########################################################################
## CONFIGURATION
########################################################################

env:
  IDRIS2_COMMIT: a09c5082c5aea25a6d3643f523efdf8fa8efb2ae
  SCHEME: scheme

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Initialise variables
        run: |
          echo "$HOME/.idris2/bin" >> $GITHUB_PATH

      # This caching step allows us to save a lot of building time by only
      # rebuilding Idris2 from boostrap if absolutely necessary
      - name: Cache Idris2
        uses: actions/cache@v2
        id: cache-idris2
        with:
          path: |
            ~/.idris2
          key: ${{ runner.os }}-${{ env.IDRIS2_COMMIT }}

      - name: Install Chez
        run: |
          sudo apt-get update
          sudo apt-get install -y chezscheme

      - name: Install Idris2
        if: steps.cache-idris2.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/idris-lang/idris2
          cd idris2
          git checkout ${{ env.IDRIS2_COMMIT }}
          make bootstrap && make install

      - name: Install idris2-elab-util
        run: |
          git clone https://github.com/stefan-hoeck/idris2-elab-util
          cd idris2-elab-util
          make install

      - name: Install idris2-sop
        run: |
          git clone https://github.com/stefan-hoeck/idris2-sop
          cd idris2-sop
          make install

      - name: Checkout idris2-tls
        uses: actions/checkout@v2

      - name: Build package
        run: idris2 --build tls.ipkg
